//! Build script — Phase 5 T2.
//!
//! Two jobs, in this order:
//!
//! 1. `tauri_build::build()`, which (among much else) reads
//!    `bundle.resources` and **copies every resource next to the executable**
//!    in `target/<profile>/`. That is what makes `BaseDirectory::Resource`
//!    resolve in `cargo run` and `tauri dev`, not only in the installer.
//! 2. Generate `resource_manifest.rs` — the list `src/resources.rs` reports
//!    against — **by reading the same `bundle.resources` map**.
//!
//! ## Why the manifest is generated rather than typed
//!
//! A hand-written list beside a config list is two lists, and the failure mode
//! is silent in the direction that matters: a resource dropped from the config
//! keeps being *reported* by a stale manifest, and the report — whose entire
//! job is to be the thing T3 and T6 check against instead of trusting the
//! bundle — says "present" about a file the bundler was never asked to ship.
//! Deriving one from the other makes that unrepresentable.
//!
//! ## Why the expected sizes are measured here
//!
//! `expected_bytes` is `std::fs::metadata(source).len()` **at build time**, not
//! a constant. Constants would have to be re-typed every time
//! `build-qemu-images.mjs` or `build-lessons.mjs` regenerates an artefact, and
//! a stale constant produces a report that cries wolf. Measured at build time
//! it answers the question actually worth asking of a packaged app: *is the
//! file next to the exe the file that was configured, whole?*
//!
//! A source that is absent at build time (a clean clone with no
//! `fetch-qemu.mjs` run) yields `None` rather than a build failure — the Tauri
//! bundler will refuse for its own reasons, with a better message, and a plain
//! `cargo check` should still work.

use std::{collections::BTreeMap, env, fs, path::Path};

fn main() {
    tauri_build::build();
    generate_resource_manifest();
}

/// Read `bundle.resources` and write `$OUT_DIR/resource_manifest.rs`.
fn generate_resource_manifest() {
    let config_path = Path::new("tauri.conf.json");
    println!("cargo:rerun-if-changed=tauri.conf.json");

    let config: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(config_path).expect("src-tauri/tauri.conf.json is unreadable"),
    )
    .expect("src-tauri/tauri.conf.json is not valid JSON");

    let resources = config
        .get("bundle")
        .and_then(|b| b.get("resources"))
        .and_then(|r| r.as_object())
        .unwrap_or_else(|| {
            panic!(
                "bundle.resources must be a source -> target MAP, not a list. The list form runs \
                 every path through tauri_utils::resources::resource_relpath, which turns each \
                 leading `..` into a literal `_up_` directory — so `../tools/qemu/...` would land \
                 at `$RESOURCE/_up_/tools/qemu/...`. Every resource in this app is outside \
                 src-tauri/, so the map form is not a preference."
            )
        });

    // BTreeMap so the generated file is byte-stable across builds; serde_json's
    // Map iteration order is insertion order for a parsed document, but the
    // manifest is compared by eye in findings and by diff in review.
    let mut entries: BTreeMap<String, String> = BTreeMap::new();
    for (source, target) in resources {
        let target = target
            .as_str()
            .expect("every bundle.resources value must be a target path string");
        assert!(
            !source.contains('*'),
            "T2 deliberately enumerates every resource instead of globbing: {source}. A glob in \
             the map form flattens matches into the target directory (dest.join(file_name)), and \
             a glob that matches nothing is a build error rather than a smaller bundle — but \
             neither is visible in the config, and this manifest could not record an expected \
             size for a file it has not enumerated."
        );
        assert!(
            !target.is_empty() && !target.ends_with('/') && !target.ends_with('\\'),
            "target {target:?} for {source:?} must be a full path INCLUDING the file name. Tauri's \
             map form treats a non-empty target for a single-file source as the complete \
             destination path (resources.rs: `dest.clone()`), so a trailing slash produces a FILE \
             named after the directory."
        );
        let previous = entries.insert(target.to_string(), source.to_string());
        assert!(
            previous.is_none(),
            "two sources are bundled to the same target {target:?}"
        );
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from tauri.conf.json -> bundle.resources. Do not edit.\n",
    );
    out.push_str("pub const BUNDLED: &[BundledResource] = &[\n");
    for (target, source) in &entries {
        // The bundler resolves resource sources relative to src-tauri/, which
        // is also build.rs's working directory — so the same string works here.
        let expected = match fs::metadata(source) {
            Ok(meta) => {
                println!("cargo:rerun-if-changed={source}");
                format!("Some({})", meta.len())
            }
            Err(_) => {
                println!(
                    "cargo:warning=bundle resource source is missing: {source} (a clean clone \
                     without tools/qemu or emulator/qemu/images; `tauri build` will refuse until \
                     it is fetched)"
                );
                "None".to_string()
            }
        };
        out.push_str(&format!(
            "    BundledResource {{ target: {target:?}, source: {source:?}, expected_bytes: {expected} }},\n"
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("resource_manifest.rs");
    fs::write(&dest, out).expect("cannot write resource_manifest.rs");
}
