#!/usr/bin/env bash
# F3 - install the portable, repo-local Arduino firmware toolchain (POSIX shell
# / Git Bash equivalent of setup-firmware-toolchain.ps1).
#
# Nothing is installed machine-wide. Everything lands under tools/.
# Every arduino-cli invocation passes --config-file: without it arduino-cli
# falls back to %LOCALAPPDATA%\Arduino15 and writes an inventory.yaml there.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(dirname "$here")"

ARDUINO_CLI_VERSION=1.5.1
ARDUINO_CLI_SHA256=fabe42e0eb04d00e776a66178299ff95a46c623dbc260f997e58fd514853dd40
ESP32_CORE_VERSION=3.3.11
# ESP32Servo pinned to 3.0.9 by upstream (firmware/README.md:42,47,175):
# newer releases can leak a write on one servo across channels, ESP32Servo#103.
LIBRARIES=(
  "ESP32Servo@3.0.9"
  "Adafruit SSD1306@2.5.17"
  "Adafruit GFX Library@1.12.6"
  "Adafruit BusIO@1.17.4"
)

cli_dir="$repo/tools/arduino-cli"
data_root="$repo/tools/arduino-data"
cli="$cli_dir/arduino-cli.exe"
cfg="$cli_dir/arduino-cli.yaml"

mkdir -p "$cli_dir" "$data_root/data" "$data_root/downloads" "$data_root/user" "$data_root/builds"

if [ ! -f "$cli" ]; then
  zip="arduino-cli_${ARDUINO_CLI_VERSION}_Windows_64bit.zip"
  echo "[cli]   downloading $zip"
  curl -sSL -o "$cli_dir/$zip" "https://downloads.arduino.cc/arduino-cli/$zip"
  actual="$(sha256sum "$cli_dir/$zip" | cut -d' ' -f1)"
  if [ "$actual" != "$ARDUINO_CLI_SHA256" ]; then
    echo "arduino-cli archive SHA-256 mismatch: expected $ARDUINO_CLI_SHA256 got $actual" >&2
    exit 1
  fi
  unzip -o -q "$cli_dir/$zip" -d "$cli_dir"
  echo "[cli]   verified + extracted"
fi
# Config file is GENERATED, not checked in (tools/ is gitignored). Absolute
# paths, because arduino-cli resolves relative directory settings against the
# process CWD rather than against this file. Two default locations leak outside
# the repo if left alone, and both were seen doing so during F3:
#   %LOCALAPPDATA%/Arduino15  data dir; also collects inventory.yaml from ANY
#                             arduino-cli call missing --config-file
#   %LOCALAPPDATA%/arduino    build_cache.path, the compilation cache
data_fwd="$(cygpath -m "$data_root" 2>/dev/null || echo "$data_root")"
cat > "$cfg" <<CFG
# GENERATED by scripts/setup-firmware-toolchain.sh - do not hand-edit.
# Portable, repo-local arduino-cli configuration for Sesame Robot Emulator F3.
build_cache:
  path: ${data_fwd}/builds
  # Never auto-purge: a cache eviction mid-experiment would silently change what
  # a "clean rebuild" actually rebuilds, which is the one thing the determinism
  # check must control for.
  compilations_before_purge: 0
board_manager:
  additional_urls:
    # Espressif's GitHub Pages host, not the raw.githubusercontent.com URL in
    # firmware/README.md:37 - raw.githubusercontent.com intermittently fails TLS
    # certificate-revocation checking on this host. Same JSON, different origin.
    - https://espressif.github.io/arduino-esp32/package_esp32_index.json
directories:
  data: ${data_fwd}/data
  downloads: ${data_fwd}/downloads
  user: ${data_fwd}/user
library:
  enable_unsafe_install: false
logging:
  level: info
  format: text
metrics:
  enabled: false
output:
  no_color: true
updater:
  enable_notification: false
CFG
echo "[cfg]   wrote $cfg"

export ARDUINO_DIRECTORIES_DATA="$(cygpath -w "$data_root/data" 2>/dev/null || echo "$data_root/data")"
export ARDUINO_DIRECTORIES_DOWNLOADS="$(cygpath -w "$data_root/downloads" 2>/dev/null || echo "$data_root/downloads")"
export ARDUINO_DIRECTORIES_USER="$(cygpath -w "$data_root/user" 2>/dev/null || echo "$data_root/user")"
export ARDUINO_BUILD_CACHE_PATH="$(cygpath -w "$data_root/builds" 2>/dev/null || echo "$data_root/builds")"

acli() { "$cli" --config-file "$cfg" "$@"; }

echo '[index] updating board manager index'
acli core update-index

echo "[core]  installing esp32:esp32@$ESP32_CORE_VERSION (multi-GB, slow first time)"
acli core install "esp32:esp32@$ESP32_CORE_VERSION"

for spec in "${LIBRARIES[@]}"; do
  echo "[lib]   $spec"
  acli lib install "$spec"
done

for leak in "$HOME/AppData/Local/Arduino15" "$HOME/AppData/Local/arduino"; do
  if [ -e "$leak" ]; then
    echo "ERROR: $leak exists - arduino-cli escaped its repo-local directories." >&2
    find "$leak" >&2
    exit 1
  fi
  echo "[check] $leak absent - no machine-wide state. OK"
done

acli core list
acli lib list
