<#
.SYNOPSIS
    Create the Phase-0 F5 asset-pipeline Python environment.

.DESCRIPTION
    Builds a private virtualenv at tools/py-assets/.venv and installs the
    exactly-pinned geometry stack into it. Nothing is installed machine-wide
    and nothing outside tools/ is touched.

    The pin list is embedded in this script and written out to
    tools/py-assets/requirements.txt on every run, so the pins survive even
    though tools/ is gitignored.

.EXAMPLE
    pwsh -File scripts/setup-asset-env.ps1
    pwsh -File scripts/setup-asset-env.ps1 -Recreate
#>
[CmdletBinding()]
param(
    [switch]$Recreate,
    [string]$Python = "python"
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvDir   = Join-Path $RepoRoot "tools/py-assets"
$VenvDir  = Join-Path $EnvDir ".venv"
$ReqFile  = Join-Path $EnvDir "requirements.txt"

$Requirements = @'
# Sesame Robot Emulator - Phase 0 task F5 asset pipeline
# Generated by scripts/setup-asset-env.ps1 / .sh - edit the pins THERE.
# Installed only into tools/py-assets/.venv. Never machine-wide.

# --- direct dependencies -------------------------------------------------
trimesh==4.12.2       # mesh measurement, adjacency, proximity, sampling
numpy==2.5.2          # linear algebra behind the cylinder fitting
numpy-stl==3.2.0      # required by the plan; secondary STL reader / validator
scipy==1.18.1         # cKDTree, used to cluster cylinder-axis votes
rtree==1.4.1          # spatial index trimesh.proximity needs for shape compare
jsonschema==4.26.0    # validates hardware/assets-inventory.json against its schema

# --- transitive, pinned for byte-reproducible environments ---------------
attrs==26.1.0
jsonschema-specifications==2025.9.1
python-utils==4.0.0
referencing==0.37.0
rpds-py==2026.6.3
six==1.17.0
typing_extensions==4.16.0
'@

if ($Recreate -and (Test-Path $VenvDir)) {
    Write-Host "removing existing venv at $VenvDir"
    Remove-Item -Recurse -Force $VenvDir
}

New-Item -ItemType Directory -Force -Path $EnvDir | Out-Null
Set-Content -Path $ReqFile -Value $Requirements -Encoding UTF8
Write-Host "wrote $ReqFile"

if (-not (Test-Path $VenvDir)) {
    Write-Host "creating venv at $VenvDir"
    & $Python -m venv $VenvDir
    if ($LASTEXITCODE -ne 0) { throw "python -m venv failed" }
}

$VenvPython = Join-Path $VenvDir "Scripts/python.exe"
if (-not (Test-Path $VenvPython)) {
    $VenvPython = Join-Path $VenvDir "bin/python"     # venv made under WSL/git-bash
}

& $VenvPython -m pip install --upgrade pip
if ($LASTEXITCODE -ne 0) { throw "pip self-upgrade failed" }

& $VenvPython -m pip install --require-virtualenv -r $ReqFile
if ($LASTEXITCODE -ne 0) { throw "dependency install failed" }

& $VenvPython -c @"
import numpy, scipy, trimesh, stl, jsonschema
print('numpy   ', numpy.__version__)
print('scipy   ', scipy.__version__)
print('trimesh ', trimesh.__version__)
print('numpy-stl + jsonschema imported ok')
"@
if ($LASTEXITCODE -ne 0) { throw "import smoke test failed" }

Write-Host ""
Write-Host "environment ready. Regenerate the inventory with:"
Write-Host "  tools/py-assets/.venv/Scripts/python.exe scripts/extract-stl-geometry.py ``"
Write-Host "    --stl-dir reference/sesame-robot-main/hardware/printing/stl ``"
Write-Host "    --cad-dir reference/sesame-robot-main/hardware/cad ``"
Write-Host "    --repo-root . --out hardware/assets-inventory.json"
