#!/usr/bin/env bash
# Create the Phase-0 F5 asset-pipeline Python environment.
#
# Builds a private virtualenv at tools/py-assets/.venv and installs the
# exactly-pinned geometry stack into it. Nothing is installed machine-wide and
# nothing outside tools/ is touched.
#
# The pin list is embedded here and written to tools/py-assets/requirements.txt
# on every run, so the pins survive even though tools/ is gitignored.
#
# Usage:
#   scripts/setup-asset-env.sh            # create or update
#   scripts/setup-asset-env.sh --recreate # wipe the venv first
set -euo pipefail

RECREATE=0
PYTHON="${PYTHON:-python}"
for arg in "$@"; do
  case "$arg" in
    --recreate) RECREATE=1 ;;
    --python=*) PYTHON="${arg#--python=}" ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="$REPO_ROOT/tools/py-assets"
VENV_DIR="$ENV_DIR/.venv"
REQ_FILE="$ENV_DIR/requirements.txt"

if [ "$RECREATE" = "1" ] && [ -d "$VENV_DIR" ]; then
  echo "removing existing venv at $VENV_DIR"
  rm -rf "$VENV_DIR"
fi

mkdir -p "$ENV_DIR"
cat > "$REQ_FILE" <<'REQ'
# Sesame Lab - Phase 0 task F5 asset pipeline
# Generated by scripts/setup-asset-env.ps1 / .sh - edit the pins THERE.
# Installed only into tools/py-assets/.venv. Never machine-wide.

# --- direct dependencies -------------------------------------------------
trimesh==4.12.2       # mesh measurement, adjacency, proximity, sampling
numpy==2.5.2          # linear algebra behind the cylinder fitting
numpy-stl==3.2.0      # required by the plan; secondary STL reader / validator
scipy==1.18.1         # cKDTree, used to cluster cylinder-axis votes
rtree==1.4.1          # spatial index trimesh.proximity needs for shape compare
jsonschema==4.26.0    # validates hardware/assets-inventory.json against its schema

# --- transitive, pinned for byte-reproducible environments ---------------
attrs==26.1.0
jsonschema-specifications==2025.9.1
python-utils==4.0.0
referencing==0.37.0
rpds-py==2026.6.3
six==1.17.0
typing_extensions==4.16.0
REQ
echo "wrote $REQ_FILE"

if [ ! -d "$VENV_DIR" ]; then
  echo "creating venv at $VENV_DIR"
  "$PYTHON" -m venv "$VENV_DIR"
fi

if [ -x "$VENV_DIR/Scripts/python.exe" ]; then
  VENV_PY="$VENV_DIR/Scripts/python.exe"          # Windows layout
else
  VENV_PY="$VENV_DIR/bin/python"
fi

"$VENV_PY" -m pip install --upgrade pip
"$VENV_PY" -m pip install --require-virtualenv -r "$REQ_FILE"

"$VENV_PY" - <<'PY'
import numpy, scipy, trimesh, stl, jsonschema
print("numpy   ", numpy.__version__)
print("scipy   ", scipy.__version__)
print("trimesh ", trimesh.__version__)
print("numpy-stl + jsonschema imported ok")
PY

cat <<'MSG'

environment ready. Regenerate the inventory with:
  tools/py-assets/.venv/Scripts/python.exe scripts/extract-stl-geometry.py \
    --stl-dir reference/sesame-robot-main/hardware/printing/stl \
    --cad-dir reference/sesame-robot-main/hardware/cad \
    --repo-root . --out hardware/assets-inventory.json
MSG
